
package com.meihuichina.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PublishRoadConditionData", targetNamespace = "http://webservice.meihuichina.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublishRoadConditionData {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRoadConditionDatas", targetNamespace = "http://webservice.meihuichina.com/", className = "com.meihuichina.webservice.GetRoadConditionDatas")
    @ResponseWrapper(localName = "getRoadConditionDatasResponse", targetNamespace = "http://webservice.meihuichina.com/", className = "com.meihuichina.webservice.GetRoadConditionDatasResponse")
    public String getRoadConditionDatas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
